version: 1.0.{build}
image: Visual Studio 2015
configuration: ReleaseNoDoc
platform: Any CPU
init:
- git config --global core.autocrlf true
install:
- nuget restore
build:
  project: VSBase.sln
  verbosity: minimal
test: off
artifacts:
- path: '**\*.vsix'
- path: 'Commenter*\**\*.nupkg'
- path: 'OutputWindow*\**\*.nupkg'
- path: 'Shell*\**\*.nupkg'
- path: 'Text*\**\*.nupkg'
cache:
- packages -> **\packages.config
